### ISSUE TITLE
Figure out if "Zones" can map to counties in this data

### ISSUE THREAD

**Issue by geanders** [zailchen/noaastormevents#11]
I think there's more on this question here:

http://www.nws.noaa.gov/geodata/catalog/wsom/html/cntyzone.htm

**Comment by geanders** [comment]
(This is concerning the value in the `CZ_TYPE` column of the original data.)

**Comment by zailchen** [comment]
Since one zone number can correspond to several county fips (it is not a one to one relationship), therefore, instead of mapping "Zones" into counties, I joined map_data with "county.regions" from package "choroplethrMaps" by states&county names.
